kind: pipeline
type: docker
name: golfr test

trigger:
  event:
    - push
    - pull_request
  branch:
    - main
    - staging

steps:
  - name: test
    image: rocker/tidyverse:4.3.2
    commands:
      - R -e 'install.packages("devtools")'
      - R -e 'devtools::install_deps(dependencies = TRUE)'
      - R -e 'devtools::test()'
